### ISSUE TITLE
남여주cc 만 가능 한 가요? ^^

### ISSUE THREAD

**Issue by kimjeongrae** [young-yeon/reservation-namyeoju#3]

**Comment by young-yeon** [comment]
우선은 그렇습니다만, 현재는 남여주 페이지에도 버그로 동작 안한다고 들었습니다...
조치를 해야하는데... 시간이 없어서 못하고 있습니다........
죄송합니다

**Comment by kimjeongrae** [comment]
아하 잘 알겠습니다^^


네이버 메일앱에서 보냈습니다.
-----Original Message-----
보낸사람: "Youngyeon ***@***.***>
받는사람: ***@***.***>
참조: ***@***.***>, ***@***.***>
날짜: 2021. 8. 30 오후 4:32:42
제목: Re: [young-yeon/Reservation-Macro] 남여주cc 만 가능 한 가요? ^^ (#3)

우선은 그렇습니다만, 현재는 남여주 페이지에도 버그로 동작 안한다고 들었습니다...
조치를 해야하는데... 시간이 없어서 못하고 있습니다........
죄송합니다
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
