### ISSUE TITLE
좋은 코드 공유해 주셔서 감사합니다. 질문 하나 드리고 싶습니다.

### ISSUE THREAD

**Issue by kwonjoowon** [young-yeon/reservation-namyeoju#4]
우선 즐거운 추석 연휴되시기를 바랍니다.
제가 관련 지식이 짧아 작성하신 코드를 읽던 중 궁금증이 생겼습니다.
다름이 아니라 남여주 cc 예약 페이지에서 날짜별 예약할 수 있는 시간대를 url에 쿼리문과 해당 날짜를 변수로 할당하셔서 알아내신 것으로 이해했는데(예를 들면 10월 01일 예약 가능한 시간대를 알고 싶으면 ?SelectedDate=20211001로 하신 것으로 이해했습니다.), 이때 사용하신 쿼리문 ?SelectedDate는 어떻게 찾으신 건지 궁금합니다.
개인적으로 열심히 구글링해서 찾아본 결과, POST 방식에서는 쿼리문이 직접적으로 드러나지 않아 fiddler를 이용하여 찾아보려 했지만 성공하지 못했습니다.
가르침을 부탁드리고자 이렇게 여쭤봅니다.
읽어주셔서 감사합니다!

**Comment by young-yeon** [comment]
정말 늦은 답변이라 지금 다는게 의미는 있나 싶지만.. 일단 말씀드리겠습니다.
먼저 저 쿼리는 GET방식으로 가져옵니다. POST가 아니라요..
지금 사이트에 들어가서 로그인 후 ?SelectedDate=20211112 로 접속해보시면 아직 열리지 않은 날짜의 예약 일정이 확인되실 겁니다. (직접 확인해보시는 편이 빠를것같습니다)
실제로 버튼을 눌러서 예약을 진행하려 하면 오픈 되지 않았다고 나오기는 하지만요..
어차피 이후 예약을 진행하는 작업 자체도 POST 넣을 필요 없이 Reserve함수를 구현해 두었길래 그냥 Selenium으로 구현했습니다.
요즘 개인적으로 개발을 별로 하질 않아서 깃허브를 들어오지를 않네요ㅜㅜ 늦어서 죄송합니다

**Comment by kwonjoowon** [comment]
아닙니다 답변 주셔서 감사합니다. 제가 개발 관련 지식이 많지 않아 개인적으로 홈페이지에서 ?SelectedDate=20211112를 get방식으로 가져오는 쿼리를 어떻게 알아내셨는지 궁금해 여쭤봤습니다! 별개로 올려주신 코드 덕분에 골프장 예약 편하게 하고 있습니다. 좋은 코드 공유해 주셔서 정말 감사드립니다!

**Comment by Byuldong** [comment]
> 아닙니다 답변 주셔서 감사합니다. 제가 개발 관련 지식이 많지 않아 개인적으로 홈페이지에서 ?SelectedDate=20211112를 get방식으로 가져오는 쿼리를 어떻게 알아내셨는지 궁금해 여쭤봤습니다! 별개로 올려주신 코드 덕분에 골프장 예약 편하게 하고 있습니다. 좋은 코드 공유해 주셔서 정말 감사드립니다!

이분야 문외한인데 오늘 우연하게 알게되어 이렇게 문의사항 남깁니다. 도움 부탁드립니다.
혹시 APP실행후 21년11월12일을 ?SelectedDate=20211112 get 방식으로 가져 올때 일정이 만료된 날짜이면 "예약가능 시간이 없습니다"라고 창이뜨고 종료되지 않는데, Reserve함수가 구현되어 일정이 있는 예를들어 22년1월3일을 선택하면 브라우져창은 해당날짜로 가서 일정들이 나오지만 매크로 실행창은 Abort되는데 혹시 그린피가 - 여서 그렇게 되는 것인지? 즉 그린피 금액이 입력된 상태에서는 Abort되지 않고 시간 선택으로 진행되는지? 아니면 이런 상황이 현재 Ver.의 Bug인지? 궁금합니다.
감사합니다.
